checks:
    javascript: true

build:
    nodes:
        my-node:
           services:
               mongo: 4
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
