checks:
    javascript: true

build:
    environment:
        mongodb: true
    nodes:
        coverage:
            services:
                mongo: 4
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
