checks:
    javascript: true

build:
    environment:
        node: v8.14.0
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        coverage:
            services:
                mongo: 4
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
