checks:
    javascript: true

build:
    environment:
        mongodb: true
    nodes:
        coverage:
            tests:
                override:
                    - command: npm test
                    coverage:
                        file: coverage/clover.xml
                        format: clover
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
